---
title: 破損状態の例外に対するコード分析規則 CA2153 (コード分析)
description: 破損状態の例外に対するコード分析規則 CA2153 について
ms.date: 02/19/2019
ms.topic: reference
author: gewarren
ms.author: gewarren
ms.openlocfilehash: 32d9c6ef19d0cf1fa869f21cff7dc90d95c44277
ms.sourcegitcommit: 05d0087dfca85aac9ca2960f86c5efd218bf833f
ms.translationtype: HT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/30/2021
ms.locfileid: "99714873"
---
# <a name="ca2153-avoid-handling-corrupted-state-exceptions"></a><span data-ttu-id="ffc6e-103">CA2153:破損状態の例外の処理を回避する</span><span class="sxs-lookup"><span data-stu-id="ffc6e-103">CA2153: Avoid handling Corrupted State Exceptions</span></span>

| | <span data-ttu-id="ffc6e-104">値</span><span class="sxs-lookup"><span data-stu-id="ffc6e-104">Value</span></span> |
|-|-|
| <span data-ttu-id="ffc6e-105">**ルール ID**</span><span class="sxs-lookup"><span data-stu-id="ffc6e-105">**Rule ID**</span></span> |<span data-ttu-id="ffc6e-106">CA2153</span><span class="sxs-lookup"><span data-stu-id="ffc6e-106">CA2153</span></span>|
| <span data-ttu-id="ffc6e-107">**カテゴリ**</span><span class="sxs-lookup"><span data-stu-id="ffc6e-107">**Category**</span></span> |[<span data-ttu-id="ffc6e-108">Security</span><span class="sxs-lookup"><span data-stu-id="ffc6e-108">Security</span></span>](security-warnings.md)|
| <span data-ttu-id="ffc6e-109">**修正が中断か中断なしであるか**</span><span class="sxs-lookup"><span data-stu-id="ffc6e-109">**Fix is breaking or non-breaking**</span></span> |<span data-ttu-id="ffc6e-110">なし</span><span class="sxs-lookup"><span data-stu-id="ffc6e-110">Non-breaking</span></span>|

## <a name="cause"></a><span data-ttu-id="ffc6e-111">原因</span><span class="sxs-lookup"><span data-stu-id="ffc6e-111">Cause</span></span>

<span data-ttu-id="ffc6e-112">[破損状態例外 (CSE)](/archive/msdn-magazine/2009/february/clr-inside-out-handling-corrupted-state-exceptions) は、メモリの破損がプロセス内に存在していることを示します。</span><span class="sxs-lookup"><span data-stu-id="ffc6e-112">[Corrupted State Exceptions (CSEs)](/archive/msdn-magazine/2009/february/clr-inside-out-handling-corrupted-state-exceptions) indicate that memory corruption exists in your process.</span></span> <span data-ttu-id="ffc6e-113">プロセスをクラッシュさせるのではなくこれらの例外をキャッチすることは、攻撃者が破損したメモリ領域にセキュリティ上の弱点を見出すことができた場合に、セキュリティ上の脆弱性となる可能性があります。</span><span class="sxs-lookup"><span data-stu-id="ffc6e-113">Catching these rather than allowing the process to crash can lead to security vulnerabilities if an attacker can place an exploit into the corrupted memory region.</span></span>

## <a name="rule-description"></a><span data-ttu-id="ffc6e-114">規則の説明</span><span class="sxs-lookup"><span data-stu-id="ffc6e-114">Rule description</span></span>

<span data-ttu-id="ffc6e-115">CSE は、プロセスが破損状態にあり、システムによってキャッチされていないことを示します。</span><span class="sxs-lookup"><span data-stu-id="ffc6e-115">CSE indicates that the state of a process has been corrupted and not caught by the system.</span></span> <span data-ttu-id="ffc6e-116">破損した状態のシナリオでは、<xref:System.Runtime.ExceptionServices.HandleProcessCorruptedStateExceptionsAttribute?displayProperty=fullName> 属性でメソッドをマークした場合に、汎用ハンドラーのみがこの例外をキャッチします。</span><span class="sxs-lookup"><span data-stu-id="ffc6e-116">In the corrupted state scenario, a general handler only catches the exception if you mark your method with the <xref:System.Runtime.ExceptionServices.HandleProcessCorruptedStateExceptionsAttribute?displayProperty=fullName> attribute.</span></span> <span data-ttu-id="ffc6e-117">既定では、[共通言語ランタイム (CLR)](../../../standard/clr.md) は、CSE の catch ハンドラーを呼び出しません。</span><span class="sxs-lookup"><span data-stu-id="ffc6e-117">By default, the [Common Language Runtime (CLR)](../../../standard/clr.md) does not invoke catch handlers for CSEs.</span></span>

<span data-ttu-id="ffc6e-118">最も安全な方法は、この種の例外をキャッチせずにプロセスをクラッシュさせることです。</span><span class="sxs-lookup"><span data-stu-id="ffc6e-118">The safest option is to allow the process to crash without catching these kinds of exceptions.</span></span> <span data-ttu-id="ffc6e-119">コードをログに記録しても、攻撃者はメモリ破損のバグを悪用できます。</span><span class="sxs-lookup"><span data-stu-id="ffc6e-119">Even logging code can allow attackers to exploit memory corruption bugs.</span></span>

<span data-ttu-id="ffc6e-120">`catch (System.Exception e)` や例外パラメーターを持たない `catch` などすべての例外をキャッチする汎用ハンドラーを使用して CSE をキャッチすると、この警告がトリガーされます。</span><span class="sxs-lookup"><span data-stu-id="ffc6e-120">This warning triggers when catching CSEs with a general handler that catches all exceptions, for example, `catch (System.Exception e)` or `catch` with no exception parameter.</span></span>

## <a name="how-to-fix-violations"></a><span data-ttu-id="ffc6e-121">違反の修正方法</span><span class="sxs-lookup"><span data-stu-id="ffc6e-121">How to fix violations</span></span>

<span data-ttu-id="ffc6e-122">この警告を解決するには、次のいずれかの操作を行います:</span><span class="sxs-lookup"><span data-stu-id="ffc6e-122">To resolve this warning, do one of the following:</span></span>

- <span data-ttu-id="ffc6e-123"><xref:System.Runtime.ExceptionServices.HandleProcessCorruptedStateExceptionsAttribute> 属性を削除してください。</span><span class="sxs-lookup"><span data-stu-id="ffc6e-123">Remove the <xref:System.Runtime.ExceptionServices.HandleProcessCorruptedStateExceptionsAttribute> attribute.</span></span> <span data-ttu-id="ffc6e-124">これにより、CSE を catch ハンドラーに渡さない既定の実行時の動作に戻ります。</span><span class="sxs-lookup"><span data-stu-id="ffc6e-124">This reverts to the default run-time behavior where CSEs are not passed to catch handlers.</span></span>

- <span data-ttu-id="ffc6e-125">特定の例外の種類をキャッチするハンドラーではなく汎用 catch ハンドラーを削除します。</span><span class="sxs-lookup"><span data-stu-id="ffc6e-125">Remove the general catch handler in preference of handlers that catch specific exception types.</span></span> <span data-ttu-id="ffc6e-126">ハンドラー コードが安全に処理できたと仮定した場合 (まれ)、これに CSE が含まれることがあります。</span><span class="sxs-lookup"><span data-stu-id="ffc6e-126">This may include CSEs, assuming the handler code can safely handle them (rare).</span></span>

- <span data-ttu-id="ffc6e-127">例外を呼び出し元に渡し、実行中のプロセスを終了させる catch ハンドラーで CSE を再スローします。</span><span class="sxs-lookup"><span data-stu-id="ffc6e-127">Rethrow the CSE in the catch handler, which passes the exception to the caller and should result in ending the running process.</span></span>

## <a name="when-to-suppress-warnings"></a><span data-ttu-id="ffc6e-128">どのようなときに警告を抑制するか</span><span class="sxs-lookup"><span data-stu-id="ffc6e-128">When to suppress warnings</span></span>

<span data-ttu-id="ffc6e-129">この規則による警告は抑制しないでください。</span><span class="sxs-lookup"><span data-stu-id="ffc6e-129">Do not suppress a warning from this rule.</span></span>

## <a name="pseudo-code-example"></a><span data-ttu-id="ffc6e-130">擬似コードの例</span><span class="sxs-lookup"><span data-stu-id="ffc6e-130">Pseudo-code example</span></span>

### <a name="violation"></a><span data-ttu-id="ffc6e-131">違反</span><span class="sxs-lookup"><span data-stu-id="ffc6e-131">Violation</span></span>

<span data-ttu-id="ffc6e-132">次の擬似コードでは、このルールにより検出されたパターンを示しています。</span><span class="sxs-lookup"><span data-stu-id="ffc6e-132">The following pseudo-code illustrates the pattern detected by this rule.</span></span>

```csharp
[HandleProcessCorruptedStateExceptions]
// Method that handles CSE exceptions.
void TestMethod1()
{
    try
    {
        FileStream fileStream = new FileStream("name", FileMode.Create);
    }
    catch (Exception e)
    {
        // Handle exception.
    }
}
```

### <a name="solution-1---remove-the-attribute"></a><span data-ttu-id="ffc6e-133">解決策 1 - 属性を削除する</span><span class="sxs-lookup"><span data-stu-id="ffc6e-133">Solution 1 - remove the attribute</span></span>

<span data-ttu-id="ffc6e-134"><xref:System.Runtime.ExceptionServices.HandleProcessCorruptedStateExceptionsAttribute> 属性を削除すると、メソッドによって破損状態の例外が処理されなくなります。</span><span class="sxs-lookup"><span data-stu-id="ffc6e-134">Removing the <xref:System.Runtime.ExceptionServices.HandleProcessCorruptedStateExceptionsAttribute> attribute ensures that Corrupted State Exceptions are not handled by your method.</span></span>

```csharp
void TestMethod1()
{
    try
    {
        FileStream fileStream = new FileStream("name", FileMode.Create);
    }
    catch (Exception e)
    {
        // Handle exception.
    }
}
```

### <a name="solution-2---catch-specific-exceptions"></a><span data-ttu-id="ffc6e-135">解決策 2 - 特定の例外をキャッチする</span><span class="sxs-lookup"><span data-stu-id="ffc6e-135">Solution 2 - catch specific exceptions</span></span>

<span data-ttu-id="ffc6e-136">汎用 catch ハンドラーを削除し、特定の例外の種類のみをキャッチします。</span><span class="sxs-lookup"><span data-stu-id="ffc6e-136">Remove the general catch handler and catch only specific exception types.</span></span>

```csharp
void TestMethod1()
{
    try
    {
        FileStream fileStream = new FileStream("name", FileMode.Create);
    }
    catch (IOException e)
    {
        // Handle IOException.
    }
    catch (UnauthorizedAccessException e)
    {
        // Handle UnauthorizedAccessException.
    }
}
```

### <a name="solution-3---rethrow"></a><span data-ttu-id="ffc6e-137">解決策 3 - 再スローする</span><span class="sxs-lookup"><span data-stu-id="ffc6e-137">Solution 3 - rethrow</span></span>

<span data-ttu-id="ffc6e-138">例外を再スローします。</span><span class="sxs-lookup"><span data-stu-id="ffc6e-138">Rethrow the exception.</span></span>

```csharp
[HandleProcessCorruptedStateExceptions]
void TestMethod1()
{
    try
    {
        FileStream fileStream = new FileStream("name", FileMode.Create);
    }
    catch (Exception e)
    {
        // Rethrow the exception.
        throw;
    }
}
```
