---
description: "詳細情報: 'Throw' ステートメントでは、'Catch' ステートメントの外側、または 'Finally' ステートメントの内側にあるオペランドを省略できません"
title: "'Throw' ステートメントでは、'Catch' ステートメントの外側、または 'Finally' ステートメントの内側にあるオペランドを省略できません"
ms.date: 07/20/2015
f1_keywords:
- vbc30666
- bc30666
helpviewer_keywords:
- BC30666
ms.assetid: a208a6ea-0e36-4bf1-8984-4de1a0e38a2a
ms.openlocfilehash: 8ab76ae9e5727388ddb77ec38f1b4e89b6a0e5d6
ms.sourcegitcommit: 10e719780594efc781b15295e499c66f316068b8
ms.translationtype: HT
ms.contentlocale: ja-JP
ms.lasthandoff: 02/14/2021
ms.locfileid: "100460840"
---
# <a name="throw-statement-cannot-omit-operand-outside-a-catch-statement-or-inside-a-finally-statement"></a><span data-ttu-id="3ba04-103">'Throw' ステートメントでは、'Catch' ステートメントの外側、または 'Finally' ステートメントの内側にあるオペランドを省略できません</span><span class="sxs-lookup"><span data-stu-id="3ba04-103">'Throw' statement cannot omit operand outside a 'Catch' statement or inside a 'Finally' statement</span></span>

<span data-ttu-id="3ba04-104">`Throw` ステートメントの外側にある `Catch` ステートメントでは、例外オブジェクトの名前を指定する必要があります。</span><span class="sxs-lookup"><span data-stu-id="3ba04-104">`Throw` statements outside of `Catch` statement must supply the name of an exception object.</span></span>  
  
 <span data-ttu-id="3ba04-105">**エラー ID:** BC30666</span><span class="sxs-lookup"><span data-stu-id="3ba04-105">**Error ID:** BC30666</span></span>  
  
## <a name="to-correct-this-error"></a><span data-ttu-id="3ba04-106">このエラーを解決するには</span><span class="sxs-lookup"><span data-stu-id="3ba04-106">To correct this error</span></span>  
  
1. <span data-ttu-id="3ba04-107">`System.Exception`から派生した例外オブジェクトの名前を指定します。</span><span class="sxs-lookup"><span data-stu-id="3ba04-107">Specify the name of an exception object derived from `System.Exception`.</span></span>  
  
2. <span data-ttu-id="3ba04-108">`Throw` ステートメントが `Catch` ブロックの内側に配置されるようにコードを再構築します。</span><span class="sxs-lookup"><span data-stu-id="3ba04-108">Restructure your code so that the `Throw` statement is inside a `Catch` block.</span></span>  
  
## <a name="see-also"></a><span data-ttu-id="3ba04-109">関連項目</span><span class="sxs-lookup"><span data-stu-id="3ba04-109">See also</span></span>

- [<span data-ttu-id="3ba04-110">Throw ステートメント</span><span class="sxs-lookup"><span data-stu-id="3ba04-110">Throw Statement</span></span>](../language-reference/statements/throw-statement.md)
- [<span data-ttu-id="3ba04-111">Try...Catch...Finally ステートメント</span><span class="sxs-lookup"><span data-stu-id="3ba04-111">Try...Catch...Finally Statement</span></span>](../language-reference/statements/try-catch-finally-statement.md)
- <xref:System.Exception?displayProperty=nameWithType>
- [<span data-ttu-id="3ba04-112">.NET での例外の処理とスロー</span><span class="sxs-lookup"><span data-stu-id="3ba04-112">Handling and throwing exceptions in .NET</span></span>](../../standard/exceptions/index.md)
